# Generated by Django 3.1.7 on 2021-03-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_modified_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ModuleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=40)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('homepage', models.URLField(blank=True)),
                ('repository', models.URLField(blank=True)),
                ('documentation', models.URLField(blank=True)),
                ('dependencies', models.ManyToManyField(blank=True, to='modules.ModuleVersion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='modules.module')),
            ],
            options={
                'ordering': ['-create_datetime'],
                'unique_together': {('module', 'version')},
            },
        ),
    ]
