# Generated by Django 3.1.7 on 2021-03-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arch', models.CharField(max_length=40)),
                ('module_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.moduleversion')),
            ],
        ),
    ]
