# Generated by Django 3.1.7 on 2021-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20210328_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelib',
            name='arch',
            field=models.CharField(default='x86_64', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='modulelib',
            unique_together={('module_version', 'name', 'os', 'arch')},
        ),
    ]
