# Generated by Django 3.2.4 on 2021-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20210328_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleversion',
            name='documentation',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleversion',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleversion',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
    ]
