# Generated by Django 3.1.7 on 2021-07-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_auto_20210704_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleversion',
            name='dependencies',
        ),
    ]
