# Generated by Django 3.1.7 on 2021-07-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_remove_moduleversion_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleversion',
            name='published',
        ),
    ]
